## General Settings
# url = "http://localhost:8500"
# enable_debugging = "true" # For development Only

[log]
level  = "INFO"  # from Ruby Logger::LEVEL
rotate = "daily" # from Ruby Logger shift_age
# file = path/to/logfile

## Common Task Settings
# Can be overridden by each app settings
[task]
max_semaphores  = 5   # Max concurrency when one node can be "pulled" by others
wait_after_fire = 15  # seconds. Don't wait if not defined
watch_timeout   = 120 # seconds
on_command_failure = "abort" # or "ignore". Default is "abort"

# You can define common task commands for all apps here.
# Available variables for command formats:
#   - @app            ... Target App's Name
#   - @remote.name    ... Node Name in Consul Cluster
#   - @remote.address ... Node's Ipaddress in Consul Cluster
#   - ENV             ... Given Environment Vars for Watch Command
before_commands = [
    "echo Task <%= @app %> Started.",
]
# exec_commands = [] # Probably different for each apps.
after_commands = [
    "echo Task <%= @app %> Ended.",
]

# Belows are not implemented yet:
# command_timeout = 60

## Settings for each Task target Application
[task.apps.foo]
# max_semaphores  = 3
# before_commands = []
exec_commands = [
    #"scp -rp <%= @remote.name %>:<%= ENV['HOME'] %>/<%= @app %> <%= ENV['HOME'] %>/"
    "scp -rp <%= @remote.address %>:<%= ENV['HOME'] %>/<%= @app %> <%= ENV['HOME'] %>/"
]

# You can specify Consul service and tag to filter the task propagation targets.
# It can be normal string or regexp; if you want to specify regexp, use the keys
# "service_regexp" or "tag_regexp".
# If you miss "service" or "service_regexp" filter, "tag" and "tag_regexp" won't
# be evaluated.
service = "foo"
tag     = "v1"
# service_regexp = "^foo(:[a-z]+)?$"
# tag_regexp = "^v[0-9]$"

[task.apps.bar]
on_command_failure = "ignore"
before_commands = []
exec_commands = [
    "date '+%FT%T' > /tmp/bar.updated_at.txt",
    "rsync -az --delete --exclude='.git*' <%= @remote.address %>:<%= ENV['HOME'] %>/<%= @app %> <%= ENV['HOME'] %>/",
]
after_commands = []
